# Application Config
spring.application.name = frontend-service
server.port = 8505
spring.profiles.active = local

# JWT Security Config
application.security.jwt.secret-key = ${JWT_SECRET}
application.security.jwt.expiration = 86400000

# Show only warnings and errors
logging.level.org.springframework = ERROR
spring.main.banner-mode = off