# Application Config
spring.application.name = budget_service
server.port = 8501
spring.profiles.active = local

# DB config
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/budgetdb
spring.datasource.username = ${DB_USER}
spring.datasource.password = ${DB_PASSWORD}

# JPA config
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.open-in-view = false

# JWT Security Config
application.security.jwt.secret-key = ${JWT_SECRET}
application.security.jwt.expiration = 86400000

# Show only warnings and errors
logging.level.org.springframework = ERROR
spring.main.banner-mode = off

# Or more fine-grained
logging.level.org.hibernate = ERROR