# Application Config
spring.application.name = email-service
server.port = 8502
spring.profiles.active = local

# DB config
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/emaildb
spring.datasource.username = ${DB_USER}
spring.datasource.password = ${DB_PASSWORD}

# JPA config
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.open-in-view = false

# JWT Security Config
application.security.jwt.secret-key = ${JWT_SECRET}
application.security.jwt.expiration = 86400000

# Basic SMTP Config (Gmail)
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = ${SPRING_MAIL_USERNAME}
spring.mail.password = ${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

# Show only warnings and errors
logging.level.org.springframework = ERROR
spring.main.banner-mode = off

# Or more fine-grained
logging.level.org.hibernate = ERROR